### ISSUE TITLE
Re-saving Authors appends author to "Authors with this role"

### ISSUE THREAD

**Issue by davidhund** [TwistedInteractive/author_roles#8] opened 2011-09-04 10:47 UTC
- Symphony 2.2.3
- Author Roles 1.0

Re-saving an author that is already part of an Author Roles Group appends another link to that author to the "Authors with this role" list...

E.g.: Say I have an Author "David Hund" linked to Author Role "Noobs". When I change/re-save the Author "David Hund" a _secondary_ link to David Hund is added to the "Authors with this role": "_David Hund_, _David Hund_"

**Comment by jonmifsud** [comment] 2011-09-27 08:08
Same issue just noticed, not too sure if it was there before as someone just drew my attention about this.

I am assuming that a new 'role' is being created every time; in fact if I had to change author role, the old role is not deleted. So its not just an added link but probably skipping a check if an entry exists.

**Comment by kanduvisla** [comment] 2012-02-09 13:11
Just tried this out in 2.2.5, but can't seem to reproduce the error. Anyone still encountering this?

**Comment by kanduvisla** [comment] 2012-05-08 08:32
Can't reproduce in S2.3 / v1.1. Closing this issue, unless someone can tell me how to reproduce this error.

**Closed as completed by kanduvisla** 2012-05-08 08:32 UTC

**Comment by jonmifsud** [comment] 2012-05-08 09:48
we were running 2.2 and been some time ago - didn't get to upgrade this yet on the particular install - so could very well be resolved since.
